server:
  port: 8083

spring:
  application:
    name: buyio-order-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-order}:${DB_PORT:5432}/db_buyio_order
    username: ${DB_USER:buyio_user}
    password: ${DB_PASSWORD:buyio_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: c3VwZXItc2VjcmV0LWtleS1mb3ItYnV5aW8tcGxhdGZvcm0tYXV0aGVudGljYXRpb24tc2VydmljZS0yMDI2

app:
  kafka:
    topic-order: OrderEvents